name: pryo_app
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+5

environment:
  sdk: '>=2.19.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  google_fonts: ^4.0.4
  get: ^4.6.5
  carousel_slider: ^4.2.1
  form_validation: ^3.0.2+2
  animated_snack_bar: ^0.3.1
  http: ^0.13.0
  provider: ^6.0.5
  google_maps_place_picker_mb: ^3.0.2
  location: ^5.0.0
  google_maps_flutter: ^2.3.1
  connectivity_plus: ^4.0.2
  flutter_rating_bar: ^4.0.1
  shared_preferences: ^2.2.0
  geolocator: ^9.0.2
  image_picker: ^1.0.2
  url_launcher: ^6.1.12
  fluttertoast: ^8.2.2
  loading_animation_widget: ^1.2.0+4
  multi_dropdown: ^2.0.0
  firebase_core: ^2.15.0
  firebase_auth: ^4.7.2
  cloud_firestore: ^4.9.1
  firebase_messaging: ^14.6.5
  firebase_storage: ^11.2.5
  flutter_chat_ui: ^1.6.9
  flutter_chat_types: ^3.6.2
  mime: ^1.0.4
  open_filex: ^4.3.2
  file_picker: ^5.3.3
  flutter_facebook_auth: ^5.0.11
  country_code_picker: ^3.0.0
  dropdown_button2: ^2.3.8
  flutter_html: any
  flutter_local_notifications: ^15.1.1
  logger: ^2.0.2+1



dependency_overrides:
  intl: ^0.18.1


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/images/Onboarding/
  #   - images/a_dot_ham.jpeg

  # example:
  fonts:
    - family: nunito
      fonts:
        - asset: assets/fonts/nunito/static/Nunito-Medium.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
flutter_intl:
  enabled: true
